### ISSUE TITLE
problem running n-copy

### ISSUE THREAD

**Issue by amir-arad** [Deathspike/npm-build-tools#4]
Hi

I can't get n-copy to work. the documentation is vague or misleading.

If I run this command from my project root: 
```bash
 ./node_modules/.bin/n-copy -s ./package.json -d ./foobar.json
```

I expect to see the foobar.json file in the project root folder, or get some kind of error. Instead the command ends successfully but I see no foobar file.

**Comment by Deathspike** [comment]
This is the correct format:

    n-clean [options] <globs>

Where:

    -s is a source folder
    -d is a destination folder

It's a raw copy of files from one place to another. It doesn't do renaming. Example:

    n-copy -s /bin -d /tmp *.js

Would copy all JavaScript files from /bin to /tmp. Standard glob rules apply.

I hope this is a bit clearer. I welcome all documentation improvements :+1:

**Comment by Deathspike** [comment]
Since there has been no further response, this issue is closed.

**Comment by jkarttunen** [comment]
Having similar probelms, trying this.

**Comment by jkarttunen** [comment]
Yep, worked,thanks. I think i used '**.*'  as a glob and it worked on Mac but not on windows.

**Comment by jkarttunen** [comment]
Suggest reopening, fixing this on windows broke it on mac. My current package.json:

    "build:assets:windows": "n-copy -s ./assets -d ./dist **/*.*",
    "build:assets:unix": "n-copy --source ./assets --destination ./dist '**/*.*'",

**Comment by Deathspike** [comment]
Try double quotes like this (in `package.json`):

  "build:assets": "n-copy --source ./assets --destination ./dist \"**/*.*\"",

It's not the prettiest thing, but will work on Mac OS X, Windows and Linux (Tested on Ubuntu).

**Comment by jkarttunen** [comment]
Confirmed working on OS X

**Comment by Deathspike** [comment]
:+1:
