### ISSUE TITLE
n-concat file output empty files

### ISSUE THREAD

**Issue by karneaud** [Deathspike/npm-build-tools#7]
I downloaded your tool to a local project and when running the command

`./node_modules/.bin/n-concat -s app/scripts/controllers | ./node_modules/.bin/n-pipe dist/scripts/app.js
`
a new file is created but the file is empty!

**Comment by karneaud** [comment]
Ran the same command but instead used `./node_modules/.bin/n-concat -s app/ > ./dist/scripts/app.js
`

Same problem....empty file

**Comment by Deathspike** [comment]
`n-concat -s app/scripts/controllers` just tells `n-concat` what the source folder is.

You haven't told it what files to look for. Do that with a glob, for example, all files in that root:

``n-concat -s app/scripts/controllers "*"`

Or recursively into folders as such:

``n-concat -s app/scripts/controllers "**/*"`

I highly recommend using the actual commands and not `./node_modules/` kind of approach.

**Comment by karneaud** [comment]
Tried your suggestion using a simple

`./node_modules/.bin/n-concat -s ./app/scripts/bower_components '**/*' > dist/scripts/angular.min.js`

nothing....do i need to actually list out file names?

**Comment by karneaud** [comment]
Also tried

`./node_modules/.bin/n-concat --source app/scripts/controllers/game.js app/scripts/models/board.js > dist/app.js` 

still nothing...

**Comment by karneaud** [comment]
`./node_modules/.bin/n-concat --source app/scripts/controllers "*.js"` seems to work for a simple directory

but 

`./node_modules/.bin/n-concat --source app/scripts/bower_components "*.js"`

nor 

`./node_modules/.bin/n-concat --source app/scripts/bower_components "**/*.js"`

seem to work

**Comment by Deathspike** [comment]
Let's break this down a little:

    ./node_modules/.bin/n-concat -s ./app/scripts/bower_components '**/*' > dist/scripts/angular.min.js

1. You're using the wrong quotes if you're on Windows, which I suspect you are. Use `"`, and not `'`.
2. If the `dist/scripts` folder does not exist, this command will fail. Use `n-pipe` instead.
3. The source path may very well be an invalid relative path on Windows. Use absolute or without `./`.

Then you mentioned something like this..

    ./node_modules/.bin/n-concat --source app/scripts/controllers/game.js app/scripts/models/board.js > dist/app.js

1. The source *must* be a **directory**, not a file. It's the path from which a scan is done.
2. You *can* provide a file name as glob, but it is not recommended to do so.

For example, finding every *.js* file in `bower_components` can be done like:

    n-concat -s app/scripts/bower_components "**/*.js"

Read up on glob notation at https://github.com/isaacs/node-glob

**Comment by karneaud** [comment]
@Deathspike 

1. I'm not using Windows. I'm on a Mac :-)
2. dist/scripts DOES in fact exist

the source path was invalid 
I'm sorry of the confusion
